version: "3"
services:
  php:
    build: docker/php
    container_name: "php-api"
    image: server-php-nginx
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
    restart: always
    networks:
      - apinetwork

  nginx:
    image: nginx
    container_name: "nginx-api"
    volumes:
      - docker/nginx/server.pem:/etc/nginx/ssl/server.pem
      - docker/nginx/server-key.pem:/etc/nginx/ssl/server-key.pem
      - docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      - apinetwork

  mysql:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: mysql-api
    volumes:
      - docker/dbdata:/var/lib/mysql
    restart: always
    tty: true
    ports:
      - "33006:3306"
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - apinetwork

networks:
  apinetwork:
    driver: bridge
